stages:
  - mirror
  - docstats
  - finalize

github_mirror:
  stage: mirror
  tags:
    - github_namboy94_push
  script:
    - git checkout master
    - git pull
    - git push git@github.com:namboy94/cookbook.git master -f
